version: '3.8'
services:

  esMaster:
    image: elasticsearch:7.7.0
    environment:
      - node.name=esMaster
      - cluster.name=elasticlab
      - network.host=0.0.0.0
      - node.master=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true

      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.http.ssl.certificate_authorities=/certs/ca/ca.crt
      - xpack.security.http.ssl.key=/certs/esMaster/esMaster.key
      - xpack.security.http.ssl.certificate=/certs/esMaster/esMaster.crt

      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=/certs/ca/ca.crt
      - xpack.security.transport.ssl.certificate=/certs/esMaster/esMaster.crt
      - xpack.security.transport.ssl.key=/certs/esMaster/esMaster.key
    command: >
      bash -c '
        if [[ ! -d /certs ]]; then
          mkdir /certs
        fi
        if [[ ! -f /certs/ca.zip ]]; then
          bin/elasticsearch-certutil ca --silent --pem -out /certs/ca.zip
          unzip /certs/ca.zip -d /certs
        fi
        if [[ ! -f /certs/esMaster/esMaster.crt ]]; then
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --pem --ip 127.0.0.1 -dns localhost -name esMaster -out /certs/esMaster.zip
          unzip /certs/esMaster.zip -d /certs 
        fi
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - esMaster:/usr/share/elasticsearch/data
      - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
#      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./logs/:/usr/share/elasticsearch/logs/
      - certs:/certs
    networks:
      - elasticlab
    ports:
      - 9200:9200
    healthcheck:
      test: curl --cacert /certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  esNode:
    image: elasticsearch:7.7.0
    environment:
      - task_id"{{.Task.Slot}}"
      - node.name=esNode_${task_id}
      - cluster.name=elasticlab
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true

      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.http.ssl.certificate_authorities=/certs/ca/ca.crt
      - xpack.security.http.ssl.key=/certs/esNode_${task_id}/esNode_${task_id}.key
      - xpack.security.http.ssl.certificate=/certs/esNode_${task_id}/esNode_${task_id}.crt

      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=/certs/ca/ca.crt
      - xpack.security.transport.ssl.certificate=/certs/esNode_${task_id}/esNode_${task_id}.crt
      - xpack.security.transport.ssl.key=/certs/esNode_${task_id}/esNode_${task_id}.key
    command: >
      bash -c '
        if [[ ! -f /certs/esNode_${task_id}/esNode_${task_id}.crt ]]; then
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --pem --ip 127.0.0.1 -dns localhost -name esNode_${task_id} -out /certs/esNode_${task_id}.zip
          unzip /certs/esNode_${task_id}.zip -d /certs 
        fi
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - esNode:/usr/share/elasticsearch/data
      - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
#      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./logs/:/usr/share/elasticsearch/logs/
      - certs:/certs
    networks:
      - elasticlab
    ports:
      - 9200
    healthcheck:
      test: curl --cacert /certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - esMaster

  kibana:
    image: kibana:7.7.0
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: https://esMaster:9200
      ELASTICSEARCH_HOSTS: https://esMaster:9200
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: $KIBANA_PASSWORD
      TELEMETRY_ENABLED: "false"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: $CERTS_DIR/kibana/kibana.key
      SERVER_SSL_CERTIFICATE: $CERTS_DIR/kibana/kibana.crt
      MONITORING_ENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: $XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
      XPACK_SECURITY_ENCRYPTIONKEY: $XPACK_SECURITY_ENCRYPTIONKEY
    volumes:
      - certs:/certs:z
    ports:
      - 5601:5601
    networks:
      - elasticlab
    depends_on:
      - esMaster

  filebeat:
    hostname: filebeat
    image: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/certs:z
    command: filebeat -e
    depends_on:
      - esMaster
      - kibana
    networks:
      - elasticlab

volumes:
  esMaster:
    driver: local
  esNode:
    driver: local
  certs:
    driver: local

networks:
  elasticlab:
    external: true
    driver: bridge
