version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - cluster.name=elastic_lab
      - cluster.initial_master_nodes=es1-01,es1-02,es1-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${MEMORY_SIZE} -Xmx${MEMORY_SIZE}"
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
    volumes:
      - certs:$CERTS_DIR
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
volumes:
  certs:
    driver: local
networks:
  elastic:
    driver: bridge