strict.perms: false

filebeat.autodiscover.providers:
  - type: docker
    hints.enabled: true

filebeat.modules:
  - module: elasticsearch

output.elasticsearch:
  hosts: ["https://es1-01:9200"]
  ssl:
    certificate_authorities: ["/etc/certs/ca/ca.crt"]
    certificate: "/etc/certs/filebeat/filebeat.crt"
    key: "/etc/certs/filebeat/filebeat.key"
  username: beats_writer
  password: HUVRzzDoxb7MTlvq5TQpzNuMMu1rHZGxABLqEb+vEG
  protocol: https
  pipelines:
    - pipeline: "filebeat-%{[agent.version]}-elasticsearch-server-pipeline"
      when:
        and:
          - equals:
              container.labels.org_label-schema_url: "https://www.elastic.co/products/elasticsearch"
          - contains:
              message: '"type": "server"'
    - pipeline: "filebeat-%{[agent.version]}-elasticsearch-deprecation-pipeline"
      when:
        and:
          - equals:
              container.labels.org_label-schema_url: "https://www.elastic.co/products/elasticsearch"
          - contains:
              message: '"type": "deprecation"'
    - pipeline: "filebeat-%{[agent.version]}-elasticsearch-audit-pipeline"
      when:
        and:
          - equals:
              container.labels.org_label-schema_url: "https://www.elastic.co/products/elasticsearch"
          - contains:
              message: '"type": "audit"'
    - pipeline: "filebeat-%{[agent.version]}-elasticsearch-slowlog-pipeline"
      when:
        and:
          - equals:
              container.labels.org_label-schema_url: "https://www.elastic.co/products/elasticsearch"
          - contains:
              message: '_slowlog'
    - pipeline: "filebeat-%{[agent.version]}-elasticsearch-gc-pipeline"
      when.equals:
        container.labels.org_label-schema_url: "https://www.elastic.co/products/elasticsearch"

setup:
  kibana:
    host: "https://kibana:5601"
    ssl:
      certificate_authorities: ["/etc/certs/ca/ca.crt"]
      certificate: "/etc/certs/filebeat/filebeat.crt"
      key: "/etc/certs/filebeat/filebeat.key"

  ilm.check_exists: false

  # dashboards:
  #   enabled: true
#  retry.enabled: true
#  retry.maximum: 3
