strict.perms: false

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false
setup.ilm.overwrite: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'https://es1-01:9200'
  username: beats_writer
  password: HUVRzzDoxb7MTlvq5TQpzNuMMu1rHZGxABLqEb+vEG
  ssl:
    certificate_authorities: ["/etc/certs/ca/ca.crt"]
    certificate: "/etc/certs/metricbeat/metricbeat.crt"
    key: "/etc/certs/metricbeat/metricbeat.key"
    # verification_mode: certificate

setup:
  kibana:
    host: "https://192.0.2.255:5601"
    ssl:
      enabled: true
      certificate_authorities: ["/etc/certs/ca/ca.crt"]
      certificate: "/etc/certs/metricbeat/metricbeat.crt"
      key: "/etc/certs/metricbeat/metricbeat.key"
      # verification_mode: certificate
